"use strict";
const PDFDocument = require("pdfkit");
const fs = require("fs");

function safe(v, fb = "-") { return (v === undefined || v === null || v === "") ? fb : v; }
function drawLine(doc) { doc.moveTo(50, doc.y).lineTo(545, doc.y).stroke(); doc.moveDown(0.5); }
function addTitle(doc, t) { doc.fontSize(20).font("Helvetica-Bold").text(t, { align: "center" }); doc.moveDown(); }
function addHeading(doc, t) { doc.fontSize(14).font("Helvetica-Bold").text(t); doc.moveDown(0.3); }
function addField(doc, l, v) { doc.fontSize(10).font("Helvetica").text(`${l}: ${safe(v)}`); }

function generatePDFReport({ project, user, room, speakers, analysis, design, outputPath }) {
    return new Promise((resolve, reject) => {
        try {
            const doc = new PDFDocument({ size: "A4", margin: 50 });
            const stream = fs.createWriteStream(outputPath);
            doc.pipe(stream);

            doc.fontSize(26).font("Helvetica-Bold").text("ACOUSTIC ENGINEERING", { align: "center" });
            doc.moveDown();
            doc.fontSize(16).font("Helvetica").text("Professional Sound System Design Report", { align: "center" });
            doc.moveDown(3);
            doc.fontSize(18).font("Helvetica-Bold").text(safe(project.name), { align: "center" });
            doc.moveDown(4);
            doc.fontSize(10).text(`Generated: ${new Date().toLocaleString()}`);
            doc.addPage();

            addTitle(doc, "1. Project Information");
            addField(doc, "Project", project.name);
            addField(doc, "Project Type", project.project_type);
            addField(doc, "Client", user.name);
            addField(doc, "Phone", user.phone);
            addField(doc, "Company", user.company);
            doc.moveDown(); drawLine(doc);

            addHeading(doc, "2. Room Geometry");
            addField(doc, "Width", `${room.width} m`);
            addField(doc, "Length", `${room.length || room.depth} m`);
            addField(doc, "Height", `${room.height} m`);
            addField(doc, "Area", `${(room.area || 0).toFixed(2)} m²`);
            addField(doc, "Volume", `${(room.volume || 0).toFixed(2)} m³`);
            doc.moveDown();

            addHeading(doc, "3. Design Method");
            addField(doc, "Design Mode", project.design_mode);
            addField(doc, "AI Strategy", design?.strategy);
            addField(doc, "Design Score", design?.score);
            doc.moveDown();

            addHeading(doc, "4. Acoustic Analysis");
            addField(doc, "Average SPL", `${safe(analysis?.averageSPL, 0)} dB`);
            addField(doc, "Minimum SPL", `${safe(analysis?.minimumSPL, 0)} dB`);
            addField(doc, "Maximum SPL", `${safe(analysis?.maximumSPL, 0)} dB`);
            addField(doc, "Uniformity", `${safe(analysis?.uniformity, 0)}%`);
            doc.moveDown();

            addHeading(doc, "5. Equipment");
            (speakers || []).forEach((spk, i) => {
                doc.fontSize(10).text(`${i + 1}. ${spk.manufacturer} ${spk.model}`);
                doc.fontSize(9).text(`   RMS: ${spk.rms_power} W | Max SPL: ${spk.max_spl} dB`);
                doc.moveDown(0.4);
            });
            doc.moveDown();

            addHeading(doc, "6. Speaker Layout");
            (design?.speakers || []).forEach(item => {
                doc.fontSize(9).text(`${item.id} | ${item.model} | X: ${Number(item.x).toFixed(2)} | Y: ${Number(item.y).toFixed(2)} | Z: ${Number(item.z || 0).toFixed(2)} | Angle: ${Number(item.angle || 0).toFixed(1)}°`);
            });
            doc.moveDown();

            addHeading(doc, "7. Bill of Quantities");
            const counts = {};
            (design?.speakers || []).forEach(item => {
                const key = `${item.manufacturer} ${item.model}`;
                counts[key] = (counts[key] || 0) + 1;
            });
            Object.entries(counts).forEach(([model, qty]) => {
                doc.fontSize(10).text(`${model} — Qty: ${qty}`);
            });
            doc.moveDown();

            addHeading(doc, "8. Notes");
            doc.fontSize(10).text("This report is generated by Acoustic Engineering. Values are engineering estimates based on supplied data.");
            doc.moveDown();
            doc.fontSize(8).text("Acoustic Engineering — Unified Platform", { align: "center" });

            doc.end();
            stream.on("finish", () => resolve(outputPath));
            stream.on("error", reject);
        } catch (e) { reject(e); }
    });
}
module.exports = { generatePDFReport };
